Calicot.UI/Controllers/ListsController.cs
using Calicot.Domain.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Calicot.UI.Controllers
{
    public class ListsController : Controller
    {
        private readonly IProduitsService produitsService;

        public ListsController(IProduitsService produitsService)
        {
            this.produitsService = produitsService ?? throw new ArgumentNullException(nameof(produitsService));
        }

        public async Task<ActionResult> Index()
        {
            var listeProduits = await produitsService.ObtenirTousProduits();
            return View(listeProduits);
        }
    }
}

Calicot.UI/Controllers/ProduitsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Calicot.Domain.Services;
using Calicot.UI.ViewModel;
using System.Globalization;

namespace Calicot.UI.Controllers
{
    public class ProduitsController : Controller
    {
        private readonly IProduitsService produitsService;

        public ProduitsController(IProduitsService produitsService)
        {
            this.produitsService = produitsService ?? throw new ArgumentNullException(nameof(produitsService));
        }

        [Route("Produits/")]
        // GET: ProduitsController
        public async Task<ActionResult> Index()
        {
            var listeProduits = await produitsService.ObtenirTousProduits();
            return View(listeProduits);
        }

        [Route("Produits/Details/{id}")]
        // GET: ProduitsController/Details/5
        public async Task<ActionResult> Details(Guid id)
        {
            var produit = await produitsService.ObtenirProduitParID(id);
            return View(produit);
        }

        [Route("Produits/Create")]
        // GET: ProduitsController/Create
        public async Task<ActionResult> Create()
        {
            var produit = new Domain.Models.Produit();
            if (!ModelState.IsValid)
            {
                return View(produit);
            }

            return View(produit);
            //return RedirectToPage("./Index");
        }

        // POST: ProduitsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProduitsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProduitsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProduitsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProduitsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [Route("Produits/Add")]
        [HttpGet]
        public ActionResult Add()
        {
            var produitView = new ProduitViewModel();
            return View(produitView);
        }


        [Route("Produits/Add")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(ProduitViewModel produitView)
        {
            // TODO upload file..

            string blobUrl = string.Empty;

            if (produitView.FormFile.Length > 0)
            {
                using (var stream = produitView.FormFile.OpenReadStream())
                {
                    blobUrl = await produitsService.UploadProduitPhoto(stream, produitView.FormFile.FileName);
                }
            }


            // map produit

            Domain.Models.Produit produit = new Domain.Models.Produit(){
                SKU = produitView.SKU,
                Description = produitView.Description,
                Couleur = produitView.Couleur,
                Marque = produitView.Marque,
                Nom = produitView.Nom,
                Modele = produitView.Modele,
                Prix = Convert.ToDecimal(produitView.Prix, CultureInfo.InvariantCulture),
                Quantite = produitView.Quantite,
                Taille = produitView.Taille.ToString(),
                PhotoURL = blobUrl
            };

            // Add to db

            var result = await produitsService.AjouterProduit(produit);

            
            //return Json(new { Status = "success", Message = "Produit ajouté" });
            

            return RedirectToAction(nameof(Index));
        }
    }
}

Calicot.UI/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Calicot.UI.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

Calicot.UI/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Calicot.UI.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

Calicot.UI/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Calicot.UI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Calicot.UI/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Calicot.UI.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Calicot.UI/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Calicot.UI.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Calicot.UI/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

Calicot.UI/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Calicot.UI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Accueil";
}

<script>
    window.onload = function () {
        window.location.href = "../Produits";
    };
</script>

Calicot.UI/Pages/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="57x57" href="~/images/favicons/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="~/images/favicons/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="~/images/favicons/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="~/images/favicons/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="~/images/favicons/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="~/images/favicons/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="~/images/favicons/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="~/images/favicons/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="~/images/favicons/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192" href="~/images/favicons/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="~/images/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="~/images/favicons/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="~/images/favicons/favicon-16x16.png">
<link rel="manifest" href="~/images/favicons/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="~/images/favicons/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

Calicot.UI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Calicot</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    @*<environment include="Development">
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>*@
    <!--<environment exclude="Development">-->
    @*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
        asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
        asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />*@
    <!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>-->


    @await Html.PartialAsync("_Favicons")

</head>
<body>
    @*<nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-page="/Index" class="navbar-brand">Calicot.UI</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-page="/Index">Home</a></li>
                        <li><a asp-page="/About">About</a></li>
                        <li><a asp-page="/Contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>*@

    <nav class="navbar navbar-light navbar-fixed-top" style="background-color: #b4f0e9;">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="~/images/logo-big.png" alt="" width="150" height="40" class="d-inline-block align-top glyphicon-align-left">

            </a>
        </div>
    </nav>

    @*<partial name="_CookieConsentPartial" />*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - Calicot</p><a href="/Produits/Add" class="btn fw-bold btn-secondary">+</a>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*<environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>*@

    @RenderSection("Scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>

Calicot.UI/Views/Produits/Add.cshtml
@model Calicot.UI.ViewModel.ProduitViewModel

@{
    Layout = "_Layout";
}

@{
    ViewData["Title"] = "Add";
}

<h2>Ajouter produit </h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="@Model.SKU" class="control-label">@Model.SKU</label>
                <input asp-for="SKU" class="form-control" />
                <span asp-validation-for="SKU" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label">Nom</label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marque" class="control-label"></label>
                <input asp-for="Marque" class="form-control" />
                <span asp-validation-for="Marque" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modele" class="control-label"></label>
                <input asp-for="Modele" class="form-control" />
                <span asp-validation-for="Modele" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Couleur" class="control-label"></label>
                <input asp-for="Couleur" class="form-control" />
                <span asp-validation-for="Couleur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Taille" class="control-label"></label>
                @*<input asp-for="Taille" class="form-control" />*@
                <select asp-for="Taille" asp-items="Html.GetEnumSelectList<Tailles>()" class="form-select form-select-lg mb-3" aria-label=".form-select-lg example"></select>
                <span asp-validation-for="Taille" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="8" maxlength="1024"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantite" class="control-label"></label>
                <input asp-for="Quantite" class="form-control" />
                <span asp-validation-for="Quantite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prix" class="control-label"></label>
                <input asp-for="Prix" class="form-control" />
                <span asp-validation-for="Prix" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FormFile" class="control-label"></label>
                @*<input id="FileUpload_FormFile" type="file" name="FileUpload.FormFile" />*@
            <input asp-for="FormFile" type="file" name="FormFile" />
            </div>
            <div class="form-group">
                <input type="submit" value="Ajouter" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retourner</a>
</div>

<script>
    $(function() {

    $("form").submit(function(e) {
        e.preventDefault();
        var f = $(this);
        $.post(f.attr("action"), f.serialize(),function(res) {
            if(res.Status==="success")
            {
               alert(res.Message);
               window.location.href = "/";
            }
        });
    });

});
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Calicot.UI/Views/Produits/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}
@model Calicot.Domain.Models.Produit


<h2>Ajouter un Produit</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="@Model.SKU" class="control-label"></label>
                <input asp-for="@Model.SKU" class="form-control" />
                <span asp-validation-for="@Model.SKU" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Nom" class="control-label"></label>
                <input asp-for="@Model.Nom" class="form-control" />
                <span asp-validation-for="@Model.Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Marque" class="control-label"></label>
                <input asp-for="@Model.Marque" class="form-control" />
                <span asp-validation-for="@Model.Marque" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Modele" class="control-label"></label>
                <input asp-for="@Model.Modele" class="form-control" />
                <span asp-validation-for="@Model.Modele" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Couleur" class="control-label"></label>
                <input asp-for="@Model.Couleur" class="form-control" />
                <span asp-validation-for="@Model.Couleur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Taille" class="control-label"></label>
                <input asp-for="@Model.Taille" class="form-control" />
                <span asp-validation-for="@Model.Taille" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Description" class="control-label"></label>
                <input asp-for="@Model.Description" class="form-control" />
                <span asp-validation-for="@Model.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Quantite" class="control-label"></label>
                <input asp-for="@Model.Quantite" class="form-control" />
                <span asp-validation-for="@Model.Quantite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Prix" class="control-label"></label>
                <input asp-for="@Model.Prix" class="form-control" />
                <span asp-validation-for="@Model.Prix" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="Produit.PhotoURL" class="control-label"></label>
                <input asp-for="Produit.PhotoURL" class="form-control" />
                <span asp-validation-for="Produit.PhotoURL" class="text-danger"></span>*@
                <label class="control-label"></label>
                <input id="FileUpload_FormFile" type="file" name="FileUpload.FormFile"/>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Calicot.UI/Views/Produits/Details.cshtml
@{
    Layout = "_Layout";
}

@model Calicot.Domain.Models.Produit
@{
}

<link href="~/css/Details.css" rel="stylesheet" />

<div style="padding-top:50px">
    <h1><a href="/"> <i class="bi bi-arrow-left-circle-fill" style="color:#6c757d"></i>
        </a></h1>
</div>


<div class="card mb-3" style="max-width: 75%; margin-top:5rem">
    <div class="row g-0">
        <div class="col-md-6">
            <img class="card-img-top" id="myImg" src="@Model.PhotoURL.Replace("productimages","thumbnails")" alt="Produit image">
            <figcaption class="figure-caption text-right">Cliquez sur l'image pour l'agrandir</figcaption>
        </div>
        <div class="col-md-6">
            <h2 style="margin-bottom:20px;">@Model.Nom</h2>

            <h6><small class="text-muted" style="padding-left:15px">SKU# @Model.SKU </small></h6>
            <div class="card-body" style="padding-right:20px;">
                <p class="card-text text-justify">@Model.Description</p>
            </div>
            <div>
                <h3 style="padding-right:20px;"><p class="card-text text-right "> $@Model.Prix CAD</p></h3>
            </div>
            @if (Model.Quantite > 0)
            {
                <a href="#" class="btn btinAjt fw-bold">Acheter</a>
            }
            else
            {
                <a class="btn btn-secondary btinAjtDis fw-bold disabled">Indisponible</a>
            }
        </div>
    </div>
</div>

<div id="imgModal" class="modal" tabindex="-1">
    <!-- The Close Button -->
    <span class="close">&times;</span>

    <!-- Modal Content (The Image) -->
    <img class="modal-content" id="img01" src="@Model.PhotoURL">

</div>

<script>
    // Get the modal
    var modal = document.getElementById("imgModal");

// Get the image and insert it inside the modal - use its "alt" text as a caption
var img = document.getElementById("myImg");
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
img.onclick = function(){
  modal.style.display = "block";
  //modalImg.src = this.src;
  //captionText.innerHTML = this.alt;
}

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}
</script>

Calicot.UI/Views/Produits/Index.cshtml
@{
    Layout = "_Layout";
}

@model IEnumerable<Calicot.Domain.Models.Produit>
@{
}

<link href="~/css/produitsIndex.css" rel="stylesheet" />
<div class="card-group border-secondary row row-cols-1 row-cols-md-4 g-6" style="display:flex;">
    @{
        int counter = 1;
#if DEBUG
        counter = 4;
#endif
    }
    

    @for (int i = 0; i < counter; i++)
    {



        @foreach (var item in Model)
        {
            @*<div class="card-group border-secondary row row-cols-1 row-cols-md-4 g-6" style="display:flex;">*@
                <div class="col" style="padding-top:30px;">
                    <div class="card" style="width: 25rem;">
                        <img src="@item.PhotoURL.Replace("productimages","thumbnails")" class="card-img-top previeimg" alt="..." style="height:372px; width:248px;">
                        <div class="card-body">
                            <h3 class="card-title text-truncate">@item.Nom</h3>
                            <p class="card-text text-truncate">@item.Description</p>
                            <a href="/Produits/Details/@item.ProduitID" class="btn fw-bold btnDetails">Details</a>

                        </div>
                        <div class="card-footer">

                            @if (item.Quantite > 0)
                            {
                                <small class="text-success fw-bold">Disponible</small>
                            }
                            else
                            {
                                <small class="alert-danger fw-bold">Indisponible</small>
                            }

                        </div>
                    </div>
                </div>
                @*<div class="col">
                        <div class="card" style="width: 25rem;">
                            <img src="@item.PhotoURL" class="card-img-top previeimg" alt="...">
                            <div class="card-body">
                                <h3 class="card-title">@item.Nom</h3>
                                <p class="card-text">@item.Description</p>
                                <a asp-page="./Details" asp-route-id="@item.ProduitID" class="btn btn-primary">Acheter</a>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card" style="width: 25rem;">
                            <img src="@item.PhotoURL" class="card-img-top previeimg" alt="...">
                            <div class="card-body">
                                <h3 class="card-title">@item.Nom</h3>
                                <p class="card-text">@item.Description</p>
                                <a asp-controller="Produits" asp-action="Details" asp-route-id="@item.ProduitID" class="btn btn-primary">Acheter</a>
                            </div>
                        </div>
                    </div>*@
            @*</div>*@
        }

    }
</div>